apiVersion: apps/v1
kind: Deployment
metadata:
  name: geradordesenha
spec:
  selector:
    matchLabels:
      app: geradordesenha
  template:
    metadata:
      labels:
        app: geradordesenha
    spec:
      containers:
      - name: geradordesenha
        image: viniciuscaol/geradordesenha:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: geradordesenha-service
spec:
  selector:
    app: geradordesenha
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listadeafazeres
spec:
  selector:
    matchLabels:
      app: listadeafazeres
  template:
    metadata:
      labels:
        app: listadeafazeres
    spec:
      containers:
      - name: listadeafazeres
        image: viniciuscaol/listadeafazeres:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: listadeafazeres-service
spec:
  selector:
    app: listadeafazeres
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort